language: node_js
suod: required
services:
  - docker
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
  - npm run build
after_success:
  - docker build -t bslbckr/mitglieder:$TRAVIS_BRANCH .
  
deploy:
  provider: script
  script: bash docker_push
  on:
    all_branches: true