version: "3.2"
services:
  postgres:
    image: postgres:10.0-alpine
    volumes:
      - type: volume
        source: gucmitglieder
        target: /var/lib/postgresql/data
    networks:
      mitglieder:
        aliases:
         - postgres
  postgrest:
    image: postgrest/postgrest:latest
    networks:
      mitglieder:
        aliases:
          - postgrest
    depends_on:
      - postgres
    environment:
      PGRST_DB_URI: postgres://postgres@postgres:5432/
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: postgres
      PGRST_SERVER_PROXY_URI: http://example.com/exmple
  frontend:
    image: bslbckr/mitglieder:master
    networks:
      mitglieder:
        aliases:
         - nginx
    depends_on:
      - postgrest
    ports:
      - "4000:80"
volumes:
  gucmitglieder:
    external: true
networks:
  mitglieder: